name: Export Culture Mauricie (DICI.ca) calendar to Artsdata (V2)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 3"  # Run at 2:00 AM EST every Wednesday
jobs:
  call-export-workflow:
    uses: ./.github/workflows/export-cms-entitiesv2.yml
    with:
      calendar_id: ${{ vars.DICI_CALENDAR_ID }}
      login_email: ${{ vars.CMS_LOGIN_EMAIL }}
    secrets:
      PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      LOGIN_PASSWORD: ${{ secrets.CMS_LOGIN_PASSWORD }}

