name: Export Tout Culture calendar to Artsdata

on:
  workflow_dispatch:

jobs:
  call-export-workflow:
    uses: ./.github/workflows/export-cms-entitiesv2.yml
    with:
      calendar_id: ${{ vars.TOUT_CULTURE_CALENDAR_ID }}
      login_email: ${{ vars.CMS_LOGIN_EMAIL }}
    secrets:
      PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      LOGIN_PASSWORD: ${{ secrets.CMS_LOGIN_PASSWORD }}
