name: Export Signe Laval calendar to Artsdata

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 3"  # Run at 1:00 AM ET every Wednesday

jobs:
  call-export-workflow:
    uses: ./.github/workflows/export-cms-entities.yml
    with:
      source: signe-laval
    secrets:
      PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
