name: Export NAC Osaka Production calendar to Artsdata

on:
  workflow_dispatch:

jobs:
  call-export-workflow:
    uses: ./.github/workflows/export-cms-entities.yml
    with:
      source: nac-cna
    secrets:
      PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}