name: Export artsculturenb calendar to Artsdata

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 4"  # Run at 5:00 AM EST (9AM GMT) every Thursday

jobs:
  call-export-workflow:
    uses: ./.github/workflows/export-cms-entities.yml
    with:
      source: artsculturenb
    secrets:
      PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
