name: Export Signe Laval calendar to Artsdata (V2)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1,3,5"  # Run at 1:00 AM EST every Monday, Wednesday and Friday
jobs:
  call-export-workflow:
    uses: ./.github/workflows/export-cms-entitiesv2.yml
    with:
      calendar_id: ${{ vars.SIGNE_LAVAL_CALENDAR_ID }}
      login_email: ${{ vars.CMS_LOGIN_EMAIL }}
    secrets:
      PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      LOGIN_PASSWORD: ${{ secrets.CMS_LOGIN_PASSWORD }}
      AWS_SES_ACCESS_KEY: ${{ secrets.AWS_SES_ACCESS_KEY }}
      AWS_SES_SECRET_ACCESS_KEY: ${{ secrets.AWS_SES_SECRET_ACCESS_KEY }}

