name: Notification Test

on:
  workflow_dispatch:

jobs:
  call-export-workflow:
    uses: ./.github/workflows/export-cms-entitiesv2.yml
    with:
      calendar_id: ${{ vars.ARTSCULTURENB_CALENDAR_ID }}
      login_email: "test@culturecreates.com"
      SENDGRID_FROM_EMAIL: ${{ vars.SENDGRID_FROM_EMAIL }}
      MEDIUM_ALERTS_EMAIL: ${{ vars.MEDIUM_ALERTS_EMAIL }}
    secrets:
      PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      LOGIN_PASSWORD: ${{ secrets.CMS_LOGIN_PASSWORD }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
